services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-php
    volumes:
      - './src:/var/www/html'
    expose:
      - "9000"
    networks:
      - laravel
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    networks:
      - laravel
    depends_on:
      - php

  mysql:
    image: mysql:8
    container_name: laravel-mysql
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 55555
      MYSQL_DATABASE: comments
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    ports:
      - "9090:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - laravel
    depends_on:
      - mysql

networks:
  laravel:
    driver: bridge
